### ISSUE TITLE
tabel 渲染问题

### ISSUE THREAD

**Issue by secsilm** [sun11/hexo-renderer-kramed#2]
我在 markdown 里写的是：

```
英文 | 中文 
:---------:|:----------:
 cell state | 单元状态
 gate | 门
```

渲染出来的结果是：

![](https://i.imgur.com/pmwsUM0.png)

好像没有样式。

**Comment by Mr-Linus** [comment]
I realize I have the same problem.My latex math formulas display correctly but the table display is incorrect. What could I do  to fix it? @sun11

**Comment by sun11** [comment]
https://github.com/mathjax/MathJax-docs/wiki/LaTeX-Tabular-environment

"MathJax doesn't implement tabular, because it is really a text-mode environment."

**Comment by Mr-Linus** [comment]
Thx.
