### ISSUE TITLE
markdown编译与mathJax在行内公式上由于_引起的不兼容问题

### ISSUE THREAD

**Issue by duskcloudxu** [sun11/hexo-renderer-kramed#4]
版本:"hexo-renderer-kramed": "^0.1.4"
在mathJax的行内公式里面如果要用上标使用_字符，但是kramed对于markdown中生成斜体的_支付的判断比mathJax优先，会把两个_之间的所有支付渲染成<em>标签。导致如果一行有两个_的话就会出现行内公式无法渲染的现象。
这是只带有一个_符号时的正常渲染。
![image](https://user-images.githubusercontent.com/26619184/42711519-c64437b4-871a-11e8-8feb-5f5076ef6eff.png)
![image](https://user-images.githubusercontent.com/26619184/42711557-e48bb51c-871a-11e8-8aad-91f9fab371bf.png)
以下是有两个_符号时的渲染
![image](https://user-images.githubusercontent.com/26619184/42711884-368968e0-871c-11e8-8176-0774a74a2cb8.png)
![image](https://user-images.githubusercontent.com/26619184/42711918-50275424-871c-11e8-97bb-536a21a71059.png)
很明显可以看到中间一段被当成斜体被框在<em>标签里面了。

**Comment by duskcloudxu** [comment]
update:单纯写$a_1+b_2$这样的行内公式问题不会复现，只有写成$a_1+b_{2}$这样才会。

**Comment by sun11** [comment]
使用前请仔细阅读readme

I've modified the inline math format, like this example below:

\`$\sigma$\`

**Comment by duskcloudxu** [comment]
好的，因为之前是在直接在网上查博客的时候安装的插件，并没有仔细阅读README,打扰了不好意思（
